### PR TITLE
Initial commit of jdat_notebooks

### PR DESCRIPTION
**Pull request by jhunkeler**
Version tag TBD

@jbcurtin @larrybradley

### CODE REVIEW

**Comment by jhunkeler** [comment]
@jbcurtin Ok great, can you create the 0.1.0 git tag on `jdat_notebooks`?

**Comment by jbcurtin** [comment]
Sure, here is the tag,
https://github.com/spacetelescope/jdat_notebooks/releases/tag/0.1.0

**Comment by larrybradley** [comment]
Thanks, @jbcurtin!

**Comment by jhunkeler** [comment]
Thank you @jbcurtin :tada:

**Pull request merged**
