### PR TITLE
Iraf 27

### PR DESCRIPTION
**Pull request by justincely**
Was just installing IRAF on my system - and it allowed me to install iraf into a python3.5 environment.  I know our docs say to use 2.7, but since this is actually requirement (not just a suggestion) this should be enforced by the packaging.

Anything I'm missing on this (or previous discussions already discarded this idea)?

### CODE REVIEW

**Comment by pllim** [comment]
I heard that there will be a Python 3 compatible version of IRAF soon. Is that right, @jhunkeler ?

**Comment by jhunkeler** [comment]
@justincely  @pllim The thing to keep in mind here is, IRAF itself has no direct dependency on Python. The reason we tell people to use Python 2.7 with IRAF is because **our software** (i.e. `stsdas`, etc.) was never updated to be Python 3.x compatible.

Perhaps there are more IRAF packages that are 2.7 dependent too, but I don't know what they are.

**Comment by justincely** [comment]
Even if some (many) of the actual packages (and IRAF in general) are fine with Python 3 - our current distribution has a dependency on python 2 for most of the tasks that people actually use.  We know that, because we tell people to only install iraf + pyraf into python 2 environments in the documentation.  So in effect, _our_ distro is python 2 dependent. 

Personally, I think this will head off installation and usage issues, and make the code enforce the documentation.  This takes the responsibility off of the user in a really simple way.  We can always remove the restriction if we ever take the step to enable py3 in our pertinent iraf packages.

Mainly, it's this dichotomy between the docs and the code that seems wrong to me.  If our documentation says "only do this" and we have the ability to enforce that, why wouldn't we?  Is there some use-case where we want to allow people to install IRAF into py3?

**Comment by pllim** [comment]
>  Is there some use-case where we want to allow people to install IRAF into py3?

It is a test on whether they read the manual. :wink:

**Comment by justincely** [comment]
@jhunkeler can you review and/or merge if you're OK with this?

**Pull request closed without merging**
