### PR TITLE
Update stsci.tools to 3.4.2.1

### PR DESCRIPTION
**Pull request by pllim**
Update `stsci.tools` to 3.4.2.1. Fix homepage. c/c @cdsontag

### CODE REVIEW

**Comment by jhunkeler** [comment]
Holding due to:

https://github.com/spacetelescope/stsci.tools/blob/3.4.2/setup.cfg#L3

**Comment by cdsontag** [comment]
Done in master.

**Comment by pllim** [comment]
Updated PR to 3.4.2.1

**Comment by jhunkeler** [comment]
🎅

**Pull request merged**
