### PR TITLE
Add verhawk v0.0.1

### PR DESCRIPTION
**Pull request by jhunkeler**
Used by https://github.com/STScI-JWST/jwst/pull/177
(Or at least it _will_ be used in AstroConda at some point)

### CODE REVIEW

**Comment by pllim** [comment]
I feel like this should be the logo:

hawk

**Comment by jhunkeler** [comment]
Ha that pretty much describes it. :stuck_out_tongue_winking_eye: 
What's the copyright on the photo?

**Comment by pllim** [comment]
Hmm... yeah, not sure if we can use that exact one. It just came up as the first image in Google search (https://www.flickr.com/photos/kylehickman/4360886380). But you get the idea. :wink:

**Comment by jhunkeler** [comment]
Boo: ":copyright: All rights reserved" + "User has disabled downloading" = no-go 

I know a couple graphic artists though.

**Pull request merged**
