### PR TITLE
Upgrade stsci.tools -> 3.4.6

### PR DESCRIPTION
**Pull request by jhunkeler**
https://github.com/spacetelescope/stsci.tools/pull/30
https://github.com/spacetelescope/stsci.tools/pull/29

### CODE REVIEW

**Comment by jhunkeler** [comment]
@mcara 🚀

**Comment by mcara** [comment]
Many thanks!

**Comment by jhunkeler** [comment]
No problem. If we merge this will it break drizzlepac and skypac?

> I will start working on updating drizzlepac and skypac to use newest bitmask.

**Comment by mcara** [comment]
it shouldn't because old functions are still there - just deprecated.

**Comment by mcara** [comment]
I'll update ``drizzlepac`` and ``skypac`` to get rid of deprecation warnings.

**Comment by jhunkeler** [comment]
Good good.. I'll go ahead and merge then :)

**Comment by pllim** [comment]
@mcara , after you update those packages, remember also to release them in AstroConda. I am already seeing those deprecation warnings.

**Pull request merged**
