### PR TITLE
Update specviz version

### PR DESCRIPTION
**Pull request by nmearl**
Requires #431.

### CODE REVIEW

**Comment by SaOgaz** [comment]
@nmearl, we need to bump pyqt down to 5.9.2, that's the newest version available in contiuum right now.  That is the version I was was using locally and everything ran fine that way, but did you want to test it out on your end to double check? 

Additionally, we need to rename pyqt5 to pyqt (pqt5 is the name in conda-forge)

**Comment by SaOgaz** [comment]
Note: @jhunkeler pulled this PR down locally, changed pyqt line, and it's building and installing.

**Comment by nmearl** [comment]
Ugh, I hate anaconda... If it's working and tests pass, go for it. If you have it set up, just run a `python setup.py test`, and if it's fine, then it should be good to go.

**Comment by SaOgaz** [comment]
Danggit... I forgot not all the tests run for me with those zenodo/curl/file corruption errors.

**Comment by nmearl** [comment]
Testing should only run the specviz tests, not the specutils tests.

**Comment by SaOgaz** [comment]
I was mis-reading my errors, it's actually issue with the IO registers telling me I already have the loaders registered.  I'm not sure why this is happening, it's a clean env and I made sure to pull the right specutils and specviz versions.

**Comment by SaOgaz** [comment]
re-cloned repo, somehow my clone got hosed... but it runs fine now, and i'm under pytq 5.9.2 so we are a go @jhunkeler

**Pull request merged**
