### PR TITLE
Update specutils to v0.5.1

### PR DESCRIPTION
**Pull request by larrybradley**
CC: @nmearl, @eteq, @SaOgaz

### CODE REVIEW

**Comment by nmearl** [comment]
Looks good, thanks @larrybradley.

**Comment by eteq** [comment]
@SaOgaz can confirm one way or another, but I think there's a plan afoot to do a v0.5.1 with a quick minor fix?  If so it might be best to wait on that (although if it's just a testing fix it might not be that important).

**Comment by SaOgaz** [comment]
Done!

**Comment by larrybradley** [comment]
Thanks, @jhunkeler!

**Pull request merged**
