### PR TITLE
crds -> 7.1.1

### PR DESCRIPTION
**Pull request by jhunkeler**
Upgrade refers to:
https://github.com/spacetelescope/crds/pull/220
https://github.com/spacetelescope/crds/pull/221
https://github.com/spacetelescope/crds/pull/222

@jaytmiller Have there been any changes to the package dependencies between 7.1.0 and 7.1.1?

### CODE REVIEW

**Comment by jaytmiller** [comment]
Yes and no.   There are a number of soft dependencies in CRDS: jwst, asdf, Parsley, fitsverify....   Possibly recursing on those.   For better or worse I'm conservative on those and don't list (or require them internally) since the fundamental tasks of bestrefs and file distribution work without them.

**Comment by jaytmiller** [comment]
Is there any reason we can't merge this?  (I'll note that I'm expecting a cleanup release following HST 2017.2 testing,  both to address late inputs and to address any potential problems we discover during testing.   Still,  I'm not sure there should be gaps in the astroconda release series for CRDS,  and this release is going into the pre-release version of JWST B7.1 pipeline code.

**Comment by rendinam** [comment]
Hi @jaytmiller , I'm handling the build this time around and am merging this change now.  Thanks for the explanation.

**Comment by jaytmiller** [comment]
Thanks!

**Pull request merged**
