### PR TITLE
Update ginga

### PR DESCRIPTION
**Pull request by jhunkeler**
## Do not merge

Reason: 
* Waiting for AstroPy release
* Waiting for version data to be updated for ginga and stginga (post-astropy release)

Fixes:
* #15 
* #16

### CODE REVIEW

**Comment by pllim** [comment]
Thanks!

**Comment by jhunkeler** [comment]
Welcome 😀

**Comment by pllim** [comment]
Update: Let's wait for Astropy **1.2.1** bug-fix release that will be released soon after 1.2. That is the recommended version based on what I saw on the `astropy-dev` mailing list.

**Comment by pllim** [comment]
More update: 1.2 is out and looks like I need this sooner than later. Can we go ahead with this today? Thanks!

**Comment by pllim** [comment]
@jhunkeler 

Ginga from master as ejeschke/ginga@2732be3539a960651273ff1806172e680ffcf1dc

`stginga` from [0.1 release](https://github.com/spacetelescope/stginga/releases/tag/0.1)

**Comment by pllim** [comment]
@jhunkeler 

Can you please change Ginga version to 2.5.20160627100500 ? It was just released to PyPi today (https://pypi.python.org/pypi/ginga). Thanks!

**Pull request merged**
