### PR TITLE
Correct ripples from glue-related package shuffle

### PR DESCRIPTION
**Pull request by rendinam**
* Adjust mosviz/setup.py on the fly to allow successful build
* Add missing dependency to glue-ginga

### CODE REVIEW

**Comment by pllim** [comment]
scipy is supposed to be *optional* dependency...

**Comment by pllim** [comment]
I am speaking for `glue-ginga`. If `mosviz` needs `scipy`, then its meta should be updated, not `glue-ginga`.

**Comment by rendinam** [comment]
I *thought* I collected output showing a glue-ginga build failure without scipy as a build dependency, but testing it again now shows success without that dependency made explicit. I will revert the glue-ginga recipe change. Apologies, and thanks for the info.

**Comment by pllim** [comment]
No problem, thanks for the quick fix.

**Pull request merged**
