### PR TITLE
hstcal 1.1.1. --> 1.2.0rc1

### PR DESCRIPTION
**Pull request by rendinam**

### CODE REVIEW

**Comment by pllim** [comment]
This is the first release candidate for HSTDP 2017.1 delivery.

**Comment by rendinam** [comment]
What determines the .# of the build? The release archives are lacking a .1 release for this year, so it seems that one was skipped or otherwise handled in a different manner than this release.

**Comment by sosey** [comment]
Are you referring to the missing HSTDP-2017.1 build?  That was a redhat 7 only update for DP and we didn't make a delivery I believe.  Or were you referring to something else?

**Comment by rendinam** [comment]
Yes, @sosey . Just referring to the missing HSTDP-2017.1 build. That explanation covers it. Thanks!

**Pull request merged**
