### PR TITLE
Dependency adjustments

### PR DESCRIPTION
**Pull request by rendinam**
Remove circular dependency from glueviz; other minor adjustments to allow isolated building of these packages to succeed.

### CODE REVIEW

**Comment by pllim** [comment]
c/c @astrofrog

**Comment by rendinam** [comment]
I didn't see a way to pull in other users from the PR creation.  Would an @-mention have sufficed in the comment?

**Comment by pllim** [comment]
@rendinam , by invoking `@username`, user should get an email notification about this PR. Or you can specifically request the user to be a reviewer, as you did with Joe (although I am not sure if it allows non-collaborator as reviewer).

**Comment by rendinam** [comment]
@pllim , I only saw local collaborators in the drop-down for reviewers, but I'll make use of @s in future PRs as necessary.  Thanks!

**Comment by pllim** [comment]
Just make sure the username has no typo, or the wrong person gets notified. :stuck_out_tongue:

**Pull request merged**
