### PR TITLE
Update drizzlepac -> 2.1.10

### PR DESCRIPTION
**Pull request by jhunkeler**
- Added `stsci.tools` dependency

### CODE REVIEW

**Comment by pllim** [comment]
Also need to bump `skypac` version for backward-compatibility. FYI.

**Comment by jhunkeler** [comment]
Do you mean like:
```yaml
build:
    - stsci.skypac >=0.9.3

run:
    - stsci.skypac >=0.9.3

```
?

Or just make sure the `skypac` recipe gets updated to 0.9.3?

**Comment by pllim** [comment]
I meant #191. Saw that after I made the comment. :smile:

**Comment by jhunkeler** [comment]
Ok, thanks 👍

**Pull request merged**
