### PR TITLE
Update pysynphot to 0.9.8.4

### PR DESCRIPTION
**Pull request by pllim**
UPDATE: Ready to merge! Bugs fixed, tests passed, and release is made.

Update pysynphot to 0.9.8.4. Clean up build files.

### CODE REVIEW

**Comment by jhunkeler** [comment]
*crosses fingers*

**Comment by pllim** [comment]
Need to fix it somemore. Hold your horses...

**Comment by pllim** [comment]
Okay, you can merge now. Thanks for your patience!

**Comment by jhunkeler** [comment]
🎅

**Pull request merged**
