### PR TITLE
drizzlepac - Fix missing dependency

### PR DESCRIPTION
**Pull request by jhunkeler**
Added `stsci.tools`

### CODE REVIEW

**Comment by pllim** [comment]
Not only that. It needs to be that latest release of `stsci.tools`. What Mihai changed was not backward-compatible.

**Comment by pllim** [comment]
Same problem with `skypac`.

**Comment by jhunkeler** [comment]
Ok, this should fix https://github.com/spacetelescope/drizzlepac/issues/46

`stsci.skypac` includes `stsci.tools` as a dependency already: https://github.com/astroconda/astroconda-contrib/blob/master/stsci.skypac/meta.yaml

**Comment by pllim** [comment]
That is not enough. You need to specify a min version.

**Pull request closed without merging**
