### PR TITLE
Update to reflect ASDF v2.2.1 release

### PR DESCRIPTION
**Pull request by drdavella**
Skipping the 2.2.0 release since there was a bug.

@rendinam I'm not sure how this works. It seems like #422 will need to be merged first, and then this one?

### CODE REVIEW

**Comment by rendinam** [comment]
Yes. If the desire is to have both the `2.1.2` and `2.2.1` releases appear on the Astroconda channel, which seems reasonable, then #422 will be merged, a build will take place to create the packages for that version, then this PR will be merged with a subsequent built to generate the packages for this version. I'll start that process now.

**Comment by drdavella** [comment]
Just let me know what you need me to do. It looks like a rebase is required now?

**Comment by rendinam** [comment]
Either that, or I can just resolve the conflict on that line when merged.

**Comment by drdavella** [comment]
Works for me.

**Comment by rendinam** [comment]
Packages for `2.1.2` and `2.2.1` are now available on the Astroconda channel.

**Pull request merged**
