### PR TITLE
Bump acstools to 2.1.0

### PR DESCRIPTION
**Pull request by pllim**
In conjunction with 2018.3 delivery.

### CODE REVIEW

**Comment by jhunkeler** [comment]
**Note**
`hstcal-2.1.0` must be released before this can be merged.

**Comment by pllim** [comment]
cc @jryon

**Comment by pllim** [comment]
Did the delivery ever happen, @rendinam ? Can this be merged?

**Comment by rendinam** [comment]
The delivery in question did happen. This should be OK to merge.

**Comment by pllim** [comment]
@rendinam , pls merge? 😄

**Pull request merged**
